GET http://localhost:3001/api/persons

###
GET http://localhost:3001/

###
DELETE http://localhost:3001/api/persons/4

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name":"daren",
    "number":"1730"
}