GET http://localhost:3001/api/persons

###
GET http://localhost:3001/

###
DELETE http://localhost:3001/api/persons/60c718e118f6032d504ffc45

###
GET http://localhost:3001/api/persons/@1
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name":"I am going to be deleted",
    "number":"0005"
}

###
PUT http://localhost:3001/api/persons/60c71a48f969ee28d81e9633
Content-Type: application/json

{
    "name":"I was reborn",
    "number":"1456"
}